#include "stm32f1xx_hal.h" // HAL core header for STM32F1
#include "RoboticArm.h"

extern "C" void SystemClock_Config(void);
extern "C" void MX_GPIO_Init(void);
extern "C" void MX_USART2_UART_Init(void);
extern "C" void MX_TIM2_Init(void);
// External init functions generated by STM32CubeMX (C linkage)

extern TIM_HandleTypeDef htim2;
// Timer handler declared in HAL TIM driver

int main(void){
    HAL_Init();
    // Initialize HAL library

    SystemClock_Config();
    // Configure system clock

    MX_USART2_UART_Init();
    MX_GPIO_Init();
    MX_TIM2_Init();
    // Initialize peripherals

    HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1);
    HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_2);

    RoboticArm arm;

    arm.moveJoint(0,45);
    arm.moveJoint(1,90);
    arm.printStatus();
    // Example: Move Joint 1 to 45° and Joint 2 to 90°

    HAL_Delay(2000)

    arm.reset();
    arm.printStatus();
    // Reset joints back to 0° and print status

    while(1){}
